volumes:
  tickets_local_postgres_data: {}
  tickets_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: tickets_local_django
    container_name: tickets_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: tickets_production_postgres
    container_name: tickets_local_postgres
    volumes:
      - tickets_local_postgres_data:/var/lib/postgresql/data
      - tickets_local_postgres_data_backups:/backups
    env_file:
      - .envs/.local/.postgres
    ports:
      - "6543:5432"

  frontend:
    image: node:latest
    container_name: tickets_local_frontend
    command: >
      sh -c "cd /app && npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - django